[build]
  command = "pip install -r requirements.txt"
  publish = "."
  functions = "functions"

[build.environment]
  PYTHON_VERSION = "3.9"
  PYTHONPATH = "."

[[redirects]]
  from = "/*"
  to = "/templates/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["pdfplumber", "pandas", "numpy", "openpyxl"] 